builds:
-
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
    - -X main.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
dist: releases
archives:
  - replacements:
    format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: pete911
    name: go-update
brews:
  - tap:
      owner: pete911
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: go-update
    homepage: "https://github.com/pete911/go-update"
    description: "Update go git projects."
    folder: Formula
    install: |
      bin.install "go-update"
